name: RegeXEcuter
author: nsordk & PlugMania
main: info.plugmania.regexecuter.RegeXEcuter
version: 1.0.0
softdepend:
description: PreWritten regex to prevent chat- & commandpatterns and perform actions towards them.
permissions:
  regex.safe:
    description: regexecuter stops watching player
    default: op